<div class="metabox-holder">

    <h3>Zarejestruj darmowe konto</h3>
    <p>Po rejestracji otrzymasz 3 na dzień zapytania o informacje na podstawie NIP.</p>
    <table class="form-table" role="presentation">
        <tbody>
        <tr>
            <th scope="row"><label for="field-nip-finder-email-register">Email</label></th>
            <td><input type="email" id="field-nip-finder-email-register"></td>
        </tr>
        <tr>
            <th scope="row">
                <button class="button button-primary" type="button" id="btn-nip-finder-register">
                    Zarejestruj
                </button>
            </th>
        </tr>
        </tbody>
    </table>
</div>
